name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_DB: my_wallet
          POSTGRES_PASSWORD: cpmOxzrjvx0Knppm6LmTgWkyPSsMMK
          POSTGRES_PORT: 5432
          POSTGRES_USER: wallet_user
        ports:
          - 5418:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-tests-result
        path: |
          coin-wallet/build/reports/tests/test/
          coin-wallet/build/JacocoReport/test/html/
          coin-wallet/build/api-spec/