name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:15.3
        env:
          POSTGRES_DB: my_wallet
          POSTGRES_PASSWORD: cpmOxzrjvx0Knppm6LmTgWkyPSsMMK
          POSTGRES_PORT: 5432
          POSTGRES_USER: wallet_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run build with Gradle Wrapper
      run: ./gradlew build
